### ISSUE TITLE
Cambiar comando del precio

### ISSUE THREAD

**Issue by brianl9995** [proyecto-chaucha/quirquincho#15]
El comando **/precio** se hace muy largo de escribir en el teléfono, una solución seria cambiarlo por **/p**

**Comment by clsource** [comment]
normalmente los comandos tienen autocompletar en telegram.
Segun veo a quirquincho le falta este comando en la configuracion. 

Es cosa de configurarlo en el panel del botfather. le dire al @cvasqxz 

gracias 👍
